Make conformance use main ErrorReporter.
Also move all conformance code from AF to Soy itself (it's still Google-only, though, due to protos)

Soy conformance tests now report all errors instead of the first error, and print friendly error messages with source lines instead of ugly stack traces.

This must be submitted after CL 108367198, since it leaves no way for SoyConformanceTest to throw on errors but ignore unbound globals from missing config.

Sample output:

INFO: From Compiling Soy -> Javascript. []
In file java/com/google/social/[]/hello/ui/test.soy:4:1: @param declarations in SoyDoc are banned. Use {@param} declarations in template headers instead. See []{template .blah}
^
In file java/com/google/social/[]/hello/ui/test.soy:5:1: Uses of <script> in Soy templates require review. See []  <script>{$x}</script>
^
ERROR: /google/src/cloud/slaks/hr-modules/[]/java/com/google/social/[]/hello/ui/BUILD:44:1: Compiling Soy -> Javascript. [] failed (Exit 1) [forge_remote_host=iou203].
Target [] failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 9.018s, Forge stats: 22/26 actions cached, 35.9s CPU used, 0.0s queue time, 0.5 MB ObjFS output, 0.0 MB local output, Critical Path: 8.57s, Forge (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%].
INFO: Still uploading to []
-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=109157509