Automated [] rollback of changelist 184555445.
*** Reason for rollback ***

Broke several Google Tasks [] projects
Example breakage:
[]

Error message:

java.lang.IllegalArgumentException: resource /javascript/template/soy/legacy_object_map_to_map.js not found

Note: manually deleted:
javascript/template/soy/legacy_object_map_to_map.js
because of a merge conflict, probably because of the follow-up CL []

*** Original change description ***

Soy JS runtime: move $$legacyObjectMapToMap to separate file.

This is a workaround for a DCE deopt bug in JSCompiler. By moving the triggering function to a separate file, it is pruned by AJD before JSCompiler can ever see it.

***

-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=184661736