On January 15 the maven repository decided to require everyone to manually update their dependencies from http to https.
https://blog.sonatype.com/central-repository-moving-to-https

This effectively means that the soy project has been broken since then with the following stack:

```
WARNING: Download from http://repo1.maven.org/maven2/com/google/guava/guava/25.1-jre/guava-25.1-jre.jar failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 501 HTTPS Required
WARNING: Download from http://maven.ibiblio.org/maven2/com/google/guava/guava/25.1-jre/guava-25.1-jre.jar failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Unknown host: maven.ibiblio.org
ERROR: An error occurred during the fetch of repository 'com_google_guava_guava':
   java.io.IOException: Error downloading [http://repo1.maven.org/maven2/com/google/guava/guava/25.1-jre/guava-25.1-jre.jar, http://maven.ibiblio.org/maven2/com/google/guava/guava/25.1-jre/guava-25.1-jre.jar] to /private/var/tmp/_bazel_samccone/25533a60e16bf2fe8b86024c76fed5ee/external/com_google_guava_guava/guava-25.1-jre.jar: Unknown host: maven.ibiblio.org
INFO: Call stack for the definition of repository 'args4j' which is a jvm_import_external (rule definition at /private/var/tmp/_bazel_samccone/25533a60e16bf2fe8b86024c76fed5ee/external/bazel_tools/tools/build_defs/repo/jvm.bzl:207:23):
 - <builtin>
 - /private/var/tmp/_bazel_samccone/25533a60e16bf2fe8b86024c76fed5ee/external/bazel_tools/tools/build_defs/repo/java.bzl:174:5
 - /Users/samccone/Desktop/repos/closure-templates/WORKSPACE:38:1
ERROR: /Users/samccone/Desktop/repos/closure-templates/java/src/com/google/template/soy/BUILD.bazel:275:1: [] depends on @com_google_guava_guava//:com_google_guava_guava in repository @com_google_guava_guava which failed to fetch. no such package '@com_google_guava_guava//': java.io.IOException: Error downloading [http://repo1.maven.org/maven2/com/google/guava/guava/25.1-jre/guava-25.1-jre.jar, http://maven.ibiblio.org/maven2/com/google/guava/guava/25.1-jre/guava-25.1-jre.jar] to /private/var/tmp/_bazel_samccone/25533a60e16bf2fe8b86024c76fed5ee/external/com_google_guava_guava/guava-25.1-jre.jar: Unknown host: maven.ibiblio.org
```

FIXES #207

GITHUB_BREAKING_CHANGES=NONE

-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=307515641