Automated [] rollback of changelist 148461637.
*** Reason for rollback ***

java/com/google/buzz/webconnection/hotlane/common/ui/chat/chatcontroller.js:268: ERROR - inconsistent return type

*** Original change description ***

Return goog.soy.data.SanitizedHtml instead of soydata.SanitizedHtml.

This finishes the move of goog.soy.data types to Closure, all the other types have been already moved. I don't move soydata.SanitizedHtml.from yet as it uses soydata.VERY_UNSAFE which is not moved yet.

Design doc: []

***

-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=148469101