Generate a goog.require for proto enums when used in Soy templates. Since proto enums are referenced in types in the generated JS files, a user can run into a forward declared error in templates without this, such as:
java/com/google/social/[]/squares/landingheaderweb/square_landing_header.soy.js:268: ERROR - Bad type annotation. Unknown type proto.[].squaresfacepile.style.Alignment
 *    alignment: proto.[].squaresfacepile.style.Alignment,

This CL fixes it by ensuring that the enum type is always available to the JS compiler.

-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=130229853