Fix type annotations
These will cause build errors in the next JSCompiler release. I fixed these in the simplest way I saw, so feel free to make your own changes if you want.

Example failures:
javascript/template/soy/soyutils_map.js:95: ERROR - Can only iterate over a (non-null) Iterable type
found   : Iterator<Array<(K|V)>>
required: Iterable
  for (const [k, v] of map.entries()) {
                       ^^^^^^^^^^^^^

[]

Patch in [] to reproduce
Tested:
    [] sample presubmit queue
    []

-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=195433062